Soma
Angelina0liveira/projetoGQSO pull request #6
Opened 2021-08-19 02:10 UTC by Angelina0liveira

2021-09-07 21:17 UTC, KailaneSC requested changes
Por favor, alterar o que foi solicitado nas revisões

2021-09-07 21:17 UTC, KailaneSC commented on calc-api/src/main/java/app/soma.java
> +            double soma = num1 + num2;
```suggestion
        try {
            
            double numero1 = Double.parseDouble(op1);
            double numero2 = Double.parseDouble(op2);
            double soma = numero1 + numero2;
```

2021-09-07 21:17 UTC, KailaneSC commented on calc-api/src/main/java/app/Controller.java
> +    return "Bem-vindos(as) a API calculadora!s";
```suggestion
    return "Bem-vindos(as) à API-calculadora!";
```

2021-09-13 23:04 UTC, Angelina0liveira commented on calc-api/src/main/java/app/soma.java
> +            double soma = num1 + num2;
Obrigada pela sua ajuda!

2021-09-13 23:12 UTC, Angelina0liveira commented
> Por favor, alterar o que foi solicitado nas revisões

Alterações realizadas!

2021-09-13 23:13 UTC, Angelina0liveira commented
> Por favor, alterar o que foi solicitado nas revisões

Alterações realizadas.

2021-09-13 23:14 UTC, merged